version: "3"
volumes:
  mapproxy_cache:

services:
  nginx_proxy:
    image: "matthewcmead/caching_tileserver"
    build:
      context: ./caching_tileserver
    ports:
     - "8080:80"
    environment: &environment
      - PROXY_HOST_TILESERVER=tileserver-gl
      - PROXY_HOST_MAPPROXY=mapproxy
      - OUTSIDE_PORT=8080
    entrypoint: "/usr/src/app/startup_nginx.sh"
    networks:
      - internal
      - default
    restart: unless-stopped
    depends_on:
      - tileserver-gl
      - mapproxy

  tileserver-gl:
    image: "matthewcmead/caching_tileserver"
    build:
      context: ./caching_tileserver
    volumes:
      - /Users/mmead/Desktop/tiles:/data
    entrypoint: "/usr/src/app/startup_tileserver-gl.sh planet_z0_z14.mbtiles"
    networks:
      - internal
    restart: unless-stopped

  mapproxy:
    image: "matthewcmead/caching_tileserver"
    build:
      context: ./caching_tileserver
    volumes:
      - mapproxy_cache:/cache
    entrypoint: "/usr/src/app/startup_mapproxy.sh"
    environment: *environment
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:
    internal: true
  default:
    driver: bridge
